apiVersion: v1
kind: Service
metadata:
  labels:
    app: neo4j
  name: neo4j
  namespace: neo4j-cluster
spec:
  clusterIP: None
  ports:
    - port: 7474
      targetPort: 7474
  selector:
    app: neo4j
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: neo4j
  name: neo4j-api
  namespace: neo4j-cluster
spec:
  ports:
    - port: 7474
      targetPort: 7474
  selector:
    app: neo4j
