id: neo4j
type: cluster
image: "https://wiki.madcore.ai/_media/app/iconproductpluginneo4j001.png"
description: "Neo4j Cluster"
bullets:
- "Data Mining"
- "Neo4j"
text_active: Active
text_buy: "$2.99"
text_inactive: Inactive
text_prerequesite: "Prerequisite missing"
frame_color: gold
cloudformations:
- name: neo4j_cluster
  stack_name: "MADCORE-Neo4jCluster"
  template_file: "cf/cluster.json"
  capabilities:
  - CAPABILITY_IAM
  parameters:
  - name: VpcId
    value: "{{ MADCORE_VPC_ID }}"
    description: VpcId
    type: string
    prompt: false
  - name: PublicNetZoneA
    value: "{{ MADCORE_PUBLIC_NET_ZONE_A }}"
    description: PublicNetZoneA
    type: string
    prompt: false
  - name: SecurityGroupCIRD
    value: "{{ (MADCORE_PRIVATE_IP.split('.')[0:3] + ['0'])|join('.') + '/24' }}"
    description: "Security Group CIRD"
    type: string
    prompt: false
  - name: MasterIP
    value: "{{ MADCORE_PRIVATE_IP }}"
    description: "IP of the master cluster node"
    type: string
    prompt: false
  - name: S3BucketName
    value: "{{ MADCORE_S3_BUCKET }}"
    description: "S3 bucket name"
    type: string
    prompt: false
  - name: KeyName
    value: "{{ MADCORE_KEY_NAME }}"
    description: "AWS KeyName"
    type: string
    prompt: false
  - name: InstanceType
    value: "{{ MADCORE_INSTANCE_TYPE }}"
    description: "AWS EC2 instance type."
    type: string
    allowed:
    - "m3.medium"
    - "m4.xlarge"
    - "r3.large"
  - name: SpotPrice
    value: "{{ InstanceType|spot_price }}"
    default_label: "{{ InstanceType|spot_price(verbose=True) }}"
    description: "AWS EC2 instance spot price."
    type: string
    cache: false
  - name: MinSize
    value: 0
    description: "Cluster MinSize."
    type: integer_positive
  - name: MaxSize
    value: 0
    description: "Cluster MaxSize."
    type: integer_positive
  - name: DesiredCapacity
    value: 0
    description: "Cluster DesiredCapacity."
    type: integer_positive
  - name: BranchName
    value: "{{ MADCORE_BRANCH }}"
    description: "Branch name"
    type: string
    prompt: false
  - name: CommitID
    value: "{{ MADCORE_COMMIT }}"
    description: "Commit ID"
    type: string
    prompt: false
jobs:
- name: cleanup
  private: true
- name: "nodes.up"
  private: true
- name: deploy
  parameters:
  - name: app_name
    value: neo4j
    description: "Plugin app name"
    type: string
  - name: nodes_ips
    value: "{{ NEO4J_CLUSTER_ASG_INSTANCE_IPS|join(',') }}"
    description: "Wait until ASG instances UP."
    type: string
    prompt: false
  sequence:
  - type: cloudformation
    name: cluster_deploy
    description: "Deploy cluster using cloudformation"
    job_name: neo4j_cluster
    action: create
  - type: job
    name: neo4j_deploy
    description: "Neo4j jenkins deploy job."
    job_name: deploy
- name: delete
  sequence:
  - type: cloudformation
    name: cluster_remove
    description: "Remove cloudformation cluster"
    job_name: neo4j_cluster
    action: delete
  - type: job
    name: neo4j_delete
    description: "Run jenkins delete job"
    job_name: delete
  - type: job
    name: nodes_cleanup
    description: "Clean up Neo4jCluster nodes."
    job_name: cleanup
- name: status
  parameters:
  - name: app_name
    value: neo4j
    description: "Plugin app name"
    type: string
  sequence:
  - type: cloudformation
    name: cluster_status
    description: "Check cloudformation cluster status"
    job_name: neo4j_cluster
    action: status
  - type: job
    name: jenkins_status
    description: "Run jenkins status job"
    job_name: status
- name: extend
  parameters:
  - name: nodes
    value: null
    description: "Extend cluster by X nodes."
    type: integer_gt_zero
  sequence:
  - type: cloudformation
    name: cluster_status
    description: "Update cloudformation cluster settings."
    job_name: neo4j_cluster
    action: update
    parameters:
    - name: InstanceType
      value: "{{ MADCORE_INSTANCE_TYPE }}"
      description: "AWS EC2 instance type."
      type: string
      allowed:
      - "m3.medium"
      - "m4.xlarge"
      - "r3.large"
    - name: SpotPrice
      value: "{{ InstanceType|spot_price }}"
      default_label: "{{ InstanceType|spot_price(verbose=True) }}"
      description: "AWS EC2 instance spot price."
      type: string
    - name: DesiredCapacity
      value: "{{ NEO4J_CLUSTER_DesiredCapacity|int + EXTEND_NODES|int }}"
      description: "Update Cluster DesiredCapacity."
      type: string
      prompt: false
    - name: MaxSize
      value: "{{ NEO4J_CLUSTER_MaxSize|int + EXTEND_NODES|int }}"
      description: "Update Cluster MaxSize."
      type: string
      prompt: false
  - type: job
    name: nodes_up
    description: "Wait until cluster nodes UP."
    job_name: "nodes.up"
    parameters:
    - name: nodes_ips
      value: "{{ NEO4J_CLUSTER_ASG_INSTANCE_IPS|join(',') }}"
      description: "Wait until ASG instances UP."
      type: string
      prompt: false
- name: contract
  parameters:
  - name: nodes
    value: null
    description: "Contract cluster by X nodes."
    type: integer_gt_zero
  sequence:
  - type: cloudformation
    name: cluster_status
    description: "Update cloudformation cluster settings"
    job_name: neo4j_cluster
    action: update
    parameters:
    - name: DesiredCapacity
      value: "{{ NEO4J_CLUSTER_DesiredCapacity|int - CONTRACT_NODES|int }}"
      description: "Update Cluster DesiredCapacity and remove X nodes."
      type: string
      prompt: false
  - type: job
    name: nodes_cleanup
    description: "Clean up cluster nodes."
    job_name: cleanup
- name: zero
  sequence:
  - type: cloudformation
    name: cluster_status
    description: "Update cloudformation cluster settings"
    job_name: neo4j_cluster
    action: update
    parameters:
    - name: DesiredCapacity
      value: 0
      description: "Set Cluster DesiredCapacity to 0."
      type: integer_positive
      prompt: false
    - name: MaxSize
      value: 0
      description: "Set Cluster MaxSize to 0."
      type: integer_positive
      prompt: false
    - name: MinSize
      value: 0
      description: "Set Cluster MinSize to 0."
      type: integer_positive
      prompt: false
  - type: job
    name: nodes_cleanup
    description: "Clean up cluster nodes."
    job_name: cleanup
