apiVersion: "apps/v1beta1"
kind: StatefulSet
metadata:
  name: neo4j-core
  namespace: neo4j-cluster
spec:
  serviceName: neo4j
  replicas: 3
  template:
    metadata:
      labels:
        app: neo4j
        role: core
    spec:
      nodeSelector:
        cluster: neo4j
      containers:
      - name: neo4j
        image: "neo4j:3.2.0-enterprise"
        imagePullPolicy: Always
        env:
          - name: NEO4J_causalClustering_initialDiscoveryMembers
            value: "neo4j-core-0.neo4j.neo4j-cluster.svc.cluster.local:5000,neo4j-core-1.neo4j.neo4j-cluster.svc.cluster.local:5000,neo4j-core-2.neo4j.neo4j-cluster.svc.cluster.local:5000"
          - name: NEO4J_dbms_mode
            value: CORE
        command: ["/bin/bash", "-c", 'export NEO4J_dbms_connectors_defaultAdvertisedAddress=$(hostname -f) && export NEO4J_causalClustering_discoveryAdvertisedAddress=$(hostname -f)::5000 &&
                                      export NEO4J_causalClustering_transactionAdvertisedAddress=$(hostname -f):6000 && export NEO4J_causalClustering_raftAdvertisedAddress=$(hostname -f):7000 &&
                                      export NEO4J_dbms.security.ha_status_auth_enabled=false && exec /docker-entrypoint.sh "neo4j"']
        ports:
        - containerPort: 5000
          name: discovery
        - containerPort: 6000
          name: tx
        - containerPort: 7000
          name: raft
        - containerPort: 7474
          name: browser
        - containerPort: 7687
          name: bolt
        securityContext:
          privileged: true
        volumeMounts:
        - name: datadir
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: datadir
      annotations:
        volume.beta.kubernetes.io/storage-class: "madcore-nfs"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
