kind: ReplicationController
apiVersion: v1
metadata:
  name: spark-ui-proxy-controller
  namespace: spark-cluster
spec:
  replicas: 1
  selector:
    component: spark-ui-proxy
  template:
    metadata:
      labels:
        component: spark-ui-proxy
    spec:
      hostNetwork: true
      containers:
        - name: spark-ui-proxy
          image: ursuad/spark-ui-proxy
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
          args:
            - spark-master:8080
          env:
            - name : URL_PREFIX
              value : "/api/v1/proxy/namespaces/spark-cluster/services/spark-ui-proxy"

          livenessProbe:
              httpGet:
                path: /
                port: 80
              initialDelaySeconds: 120
              timeoutSeconds: 5
