apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: flasker-hub
  name: flasker-hub
  namespace: flasker-hub-plugin
spec:
  replicas: 1
  selector:
    name: flasker-hub
  template:
    metadata:
      labels:
        name: flasker-hub
    spec:
      hostNetwork: true
      containers:
      - name: flasker-hub
        image: madcore/flasker:latest
