apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: chatterbot
  name: chatterbot
  namespace: chatterbot-plugin
spec:
  replicas: 1
  selector:
    name: chatterbot
  template:
    metadata:
      labels:
        name: chatterbot
    spec:
      containers:
      - name: chatterbot
        image: madcore/chatterbot:latest
