apiVersion: v1
kind: Service
metadata:
  labels:
    name: chatterbot-service
  name: chatterbot-service
  namespace: chatterbot-plugin
spec:
  ports:
  - port: 9019
    targetPort: 9019
  selector:
    name: chatterbot
