apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: pdfkit
  name: pdfkit
  namespace: pdfkit-plugin
spec:
  replicas: 1
  selector:
    name: pdfkit
  template:
    metadata:
      labels:
        name: pdfkit
    spec:
      containers:
      - name: pdfkit
        image: madcore/pdfkit:latest
