Name: "social"
Replicas: 3
Image: "madcore/social"
ImageTag: "0.10.0.1"
ImagePullPolicy: "Always"
Cpu: "100m"
Memory: "512Mi"
MaxCpu: "200m"
MaxMemory: "1024Mi"
Storage: "1Gi"
DataDirectory: "/opt/social/data"
Component: "social"

social:
  Name: "social"
  Component: "social"
  StorageClass: "madcore-nfs"
  Storage: "5Gi"
  Memory: "512Mi"
  Cpu: "300m"
