apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: deeplearning4j-examples
  name: deeplearning4j-examples
spec:
  replicas: 1
  selector:
    name: deeplearning4j-examples
  template:
    metadata:
      labels:
        name: deeplearning4j-examples
    spec:
      nodeSelector:
        role: gpu
      containers:
      - name: deeplearning4j-examples
        image: madcore/deeplearning4j:latest
        securityContext:
          privileged: true
        resources:
          limits:
            alpha.kubernetes.io/nvidia-gpu: 1
        volumeMounts:
        - mountPath: /usr/local/nvidia/bin
          name: bin
        - mountPath: /usr/lib/nvidia
          name: lib
      volumes:
      - hostPath:
          path: /usr/lib/nvidia-375/bin
        name: bin
      - hostPath:
          path: /usr/lib/nvidia-375
        name: lib
