apiVersion: v1
kind: Service
metadata:
  name: es-discovery
  namespace: es-cluster
spec:
  selector:
    component: es-discovery
  ports:
  - name: transport
    port: 9300
    protocol: TCP
    targetPort: 9300
