apiVersion: v1
kind: Service
metadata:
  name: es-master
  namespace: es-cluster
spec:
  ports:
    - port: 9300
      targetPort: 9300
      name: es
    - port: 9200
      targetPort: 9200
      name: http
  selector:
    component: es-master
