apiVersion: v1
kind: Secret
metadata:
  name: gsec
  namespace: "{{ .Values.namespace }}"
type: Opaque
data:
  RemoteUser: {{ .Values.sec.RemoteUser }}
  PathBase: {{ .Values.sec.PathBase }}
  PathData: {{ .Values.sec.PathData }}
  PathApp: {{ .Values.sec.PathApp }}
  ClientId: {{ .Values.sec.ClientId }}
  ClientSecret: {{ .Values.sec.ClientSecret }}
  RefreshToken: {{ .Values.sec.RefreshToken }}
