apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ template "fullname" . }}
  namespace: "{{ .Values.namespace }}"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  serviceName: {{ template "fullname" . }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        restartPolicy: Never
        resources:
{{ toYaml .Values.resources | indent 12 }}
        env:
        - name: REMOTE_USER
          valueFrom:
            secretKeyRef:
              name: gsec
              key: REMOTE_USER
        volumeMounts:
        - name: datadir
          mountPath: "{{ .Values.storage.DataDirectory }}"
  volumeClaimTemplates:
  - metadata:
      name: datadir
      annotations:
        volume.beta.kubernetes.io/storage-class: "{{ .Values.storage.StorageClass }}"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.storage.Size }}
