# Default values for offlineimap.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
namespace: offlineimap
image:
  repository: madcore/offlineimap
  tag: latest
  pullPolicy: Always
service:
  name: offlineimap
  type: ClusterIP
  externalPort: 9019
  internalPort: 9019
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
storage:
  StorageClass: "madcore-nfs"
  Size: "5Gi"
  DataDirectory: "/opt/offlineimap/data"
